[tool.poetry]
name = "fisheye-ui"
version = "1.0.0-beta.2"
description = "UI for FishEye"
authors = ["Madison Van Horn <67763032+madivanhorn@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
[tool.poetry.dependencies]
python = "^3.10"
fisheye = {git = "https://github.com/fisheye-sonar/fisheye.git"}
fastapi = {extras = ["standard"], version = "^0.138.0"}
pydantic = "^2.13.4"
setuptools = "<72"
torch = "2.6.0"
ultralytics = "8.3.74"
pre-commit = "^4.6.1"


[tool.poetry.scripts]
fisheye-ui = "fisheye_ui.app:main"

[tool.poetry.group.dev.dependencies]
black = "^26.5.1"
pyinstaller = {version = "^6.21.0", python = ">=3.10,<3.16"}
pytest = "^9.1.1"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
