name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["fisheye-ui"]
assignees:
  - madivanhorn
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you continue,
        it's worth checking [Troubleshooting](https://github.com/fisheye-sonar/fisheye-ui/blob/main/docs/troubleshooting/troubleshooting.md)
        in case there's already a fix for what you're seeing.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system were you running FishEye on?
      options:
        - Windows
        - macOS
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: FishEye Version
      description: What version of FishEye are you running? You can find the version number in the bottom-right corner of the app.
      placeholder: e.g., v1.0.0-beta.2
    validations:
      required: true
  - type: textarea
    id: what-were-you-doing
    attributes:
      label: What were you trying to do?
      placeholder: Tell us what you were doing when the problem happened.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      description: Include any error message you received, if any.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        If the problem happened during processing, please copy and paste the log
        from the "Show log" panel on the progress screen. This will be automatically
        formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Please don't upload sonar data publicly unless you're comfortable sharing it.